#!/bin/bash

# A tool to use a fake CA to sign a csr
# It takes a list of hosts for which csrs should be signed

# Required envars: CA_PASSWORD
# Optional envars: CA_CONFIG

usage() {
    cat <<EOF
Usage: $0 <filename> [<filename> ...]
EOF
    exit 1
}

[[ $1 ]] || usage

if [[ ! $CA_PASSWORD ]]; then
    echo "You must set the envar CA_PASSWORD"
    exit 1
fi

if [[ ! $CA_CONFIG ]]; then
    CA_CONFIG=ca.conf
fi

for FILE_NAME in "$@"; do
    DIRNAME=$(dirname "$FILE_NAME")
    BASENAME=$(basename "$FILE_NAME" .csr)
    openssl ca \
        -in "$FILE_NAME" \
        -notext \
        -out "$DIRNAME/$BASENAME.crt" \
        -config "$CA_CONFIG" \
        -extensions v3_req \
        -batch \
        -passin "pass:$CA_PASSWORD" \
        -extensions "usr_cert"

    echo "Signed certificate in $DIRNAME/$BASENAME.crt"
done
